# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'HomeServer'

variables:
  buildConfiguration: 'Release'

steps:

#Wait for the Azure team to fix this
- task: UseDotNet@2
  displayName: 'Use DotNet 3.0'
  inputs:
    packageType: 'sdk'
    version: '$(DotnetVersion)'
    installationPath: '$(TEMP)\dotnet'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet - Restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet - Build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet - Publish $(buildConfiguration) x64'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/DiVA.csproj'
    arguments: '--configuration $(BuildConfiguration)  -r win-x64 --self-contained true /p:useapphost=true --output $(Build.ArtifactStagingDirectory)\Release_x64'

- task: ArchiveFiles@2
  displayName: 'Archive x64'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\Release_x64'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\Release\DiVA_x64.zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet - Publish $(buildConfiguration) x86'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/DiVA.csproj'
    arguments: '--configuration $(BuildConfiguration)  -r win-x86 --self-contained true /p:useapphost=true --output $(Build.ArtifactStagingDirectory)\Release_x86'

- task: ArchiveFiles@2
  displayName: 'Archive x86'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\Release_x86'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\Release\DiVA_x86.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Release'